name: Desktop/JVM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Compose Desktop app with Gradle
        run: ./gradlew :example-apps:desktop:build

#  package:
#
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        include:
#          - name: Linux
#            os: ubuntu-latest
#            package: packageDeb
#            gradle: ./gradlew
#          - name: Windows
#            os: windows-latest
#            package: packageMsi
#            gradle: .\gradlew
#          - name: macOS
#            os: macos-latest
#            package: packageDmg
#            gradle: ./gradlew
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: set up JDK 16
#        uses: actions/setup-java@v2
#        with:
#          java-version: '16'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#        if: matrix.os != 'windows-latest'
#
#      - name: Package for ${{ matrix.name }}
#        run: ${{ matrix.gradle}} :example-apps:desktop:${{ matrix.package }}